# Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код
COPY . .

# Строим приложение
RUN npm run build

# Stage 2: Run
FROM node:18 AS runner

WORKDIR /app

# Копируем собранный фронтенд
COPY --from=builder /app ./

# Экспортируем переменные окружения
ENV NODE_ENV=production
ENV PORT=3000

# Запуск фронтенда
CMD ["npm", "run", "start"]
