version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    command:
      [
        "sh",
        "-c",
        "alembic revision --autogenerate -m 'Initial migration' && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000",
      ]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-run
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    command: ["npm", "run", "start"]
