###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
	"email": "user1@gmail.com",
    "password": "user1"
}


###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
	"email": "user2@gmail.com",
    "password": "user2",
    "username": "user2"
}


###
GET http://127.0.0.1:8000/users
Content-Type: application/json
